# Generated by Django 6.0.1 on 2026-01-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('filieres', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=300)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('hours_planned', models.FloatField(default=0)),
                ('hours_done', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.PositiveSmallIntegerField()),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('hours_cm', models.PositiveSmallIntegerField(default=0)),
                ('hours_td', models.PositiveSmallIntegerField(default=0)),
                ('hours_tp', models.PositiveSmallIntegerField(default=0)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('slot', models.CharField(choices=[('AM', '07h30 – 11h30'), ('PM', '12h30 – 16h30')], max_length=2)),
                ('filiere', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=150)),
                ('session_type', models.CharField(choices=[('CM', 'CM'), ('TD', 'TD'), ('TP', 'TP')], max_length=2)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.teacher')),
            ],
            options={
                'unique_together': {('day', 'slot', 'room'), ('day', 'slot', 'teacher')},
            },
        ),
    ]
